; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/page/projectconf.html

[env:esp32solo1]
platform                = espressif32
framework               = arduino
board                   = esp32-solo1
build_flags             = -DLED_BUILTIN=2
lib_ignore              = wifi
                          ble
                          dsp
                          spiffs
                          NetworkClientSecure
                          Matter
                          Zigbee
                          ESP RainMaker
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/network_provisioning
                          espressif/mdns
                          espressif/esp-dsp
                          espressif/esp_modem
                          espressif/esp32-camera
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/qrcode
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          chmorgan/esp-libhelix-mp3

[env:esp32-c2-devkitm-1]
platform                = espressif32
framework               = arduino
board                   = esp32-c2-devkitm-1
monitor_speed           = 115200
lib_ignore              = wifi
                          ble
                          dsp
                          spiffs
                          NetworkClientSecure
                          Matter
                          Zigbee
                          ESP RainMaker
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/network_provisioning
                          espressif/mdns
                          espressif/esp-dsp
                          espressif/esp_modem
                          espressif/esp32-camera
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/qrcode
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          chmorgan/esp-libhelix-mp3
custom_component_add    = espressif/cmake_utilities @ 0.*

[env:esp32-s3-arduino_nano_esp32]
platform                = espressif32
framework               = arduino
board                   = arduino_nano_esp32
monitor_speed           = 115200
lib_ignore              = wifi
                          ble
                          dsp
                          spiffs
                          NetworkClientSecure
                          Matter
                          Zigbee
                          ESP RainMaker
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/network_provisioning
                          espressif/mdns
                          espressif/esp-dsp
                          espressif/esp_modem
                          espressif/esp32-camera
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/qrcode
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          chmorgan/esp-libhelix-mp3

[env:esp32s3-qio_opi_per]
; OPI Performance settings -> Display use
platform                = espressif32
framework               = arduino
board                   = esp32s3_120_16_8-qio_opi
lib_ignore              = wifi
                          ble
                          dsp
                          spiffs
                          NetworkClientSecure
                          Matter
                          Zigbee
                          ESP RainMaker
custom_sdkconfig        = CONFIG_LCD_RGB_ISR_IRAM_SAFE=y
                          CONFIG_GDMA_CTRL_FUNC_IN_IRAM=y
                          CONFIG_I2S_ISR_IRAM_SAFE=y
                          CONFIG_GDMA_ISR_IRAM_SAFE=y
                          CONFIG_SPIRAM_XIP_FROM_PSRAM=y
                          CONFIG_SPIRAM_FETCH_INSTRUCTIONS=y
                          CONFIG_SPIRAM_RODATA=y
                          CONFIG_ESP32S3_DATA_CACHE_64KB=y
                          CONFIG_ESP32S3_DATA_CACHE_LINE_64B=y
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/network_provisioning
                          espressif/mdns
                          espressif/esp-dsp
                          espressif/esp_modem
                          espressif/esp32-camera
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/qrcode
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          chmorgan/esp-libhelix-mp3

[env:esp32-c6-devkitc-1]
platform                = espressif32
framework               = arduino
build_type              = debug
board                   = esp32-c6-devkitc-1
monitor_speed           = 115200
lib_ignore              = wifi
                          ble
                          dsp
                          spiffs
                          NetworkClientSecure
                          Matter
                          Zigbee
                          ESP RainMaker
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/network_provisioning
                          espressif/mdns
                          espressif/esp-dsp
                          espressif/esp_modem
                          espressif/esp32-camera
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/qrcode
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          chmorgan/esp-libhelix-mp3

[env:esp32-c61-devkitc1-n8r2]
platform                = espressif32
framework               = arduino
board                   = esp32-c61-devkitc1-n8r2
monitor_speed           = 115200
lib_ignore              = wifi
                          ble
                          dsp
                          spiffs
                          NetworkClientSecure
                          Matter
                          Zigbee
                          ESP RainMaker
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/network_provisioning
                          espressif/mdns
                          espressif/esp-dsp
                          espressif/esp_modem
                          espressif/esp32-camera
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/qrcode
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          chmorgan/esp-libhelix-mp3

[env:esp32-h2-devkitm-1]
platform                = espressif32
framework               = arduino
board                   = esp32-h2-devkitm-1
monitor_speed           = 115200
lib_ignore              = ble
                          dsp
                          spiffs
                          NetworkClientSecure
                          Matter
                          Zigbee
                          ESP RainMaker
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/network_provisioning
                          espressif/mdns
                          espressif/esp-dsp
                          espressif/esp_modem
                          espressif/esp32-camera
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/qrcode
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          chmorgan/esp-libhelix-mp3

[env:esp32-p4-generic]
platform                = espressif32
framework               = arduino
board                   = esp32-p4
build_flags             = -DLED_BUILTIN=2
lib_ignore              = wifi
                          ble
                          dsp
                          spiffs
                          NetworkClientSecure
                          Matter
                          Zigbee
                          ESP RainMaker
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/network_provisioning
                          espressif/mdns
                          espressif/esp-dsp
                          espressif/esp_modem
                          espressif/esp32-camera
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/qrcode
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          chmorgan/esp-libhelix-mp3
